sudo: false
language: node_js
node_js:
   - 12

install:
  - yarn install --frozen-lockfile

script: 
  - yarn lint
  - yarn lint:fix

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app:
    master: codya
    staging: codya-canary

notifications:
  email: false
